### ISSUE TITLE
Help obtaining output value

### ISSUE THREAD

**Issue by jreyes81** [jreyes81/rescuerobot#3]
Ive been a bit stuck on obtaining the output value from a function. The module "robot_stop.py" draws a stop button on the radar display, that when it gets clicked it assigns the boolean value "True" to a local variable called "stop". This module is imported to the "pygame_radar.py" file and is called inside the "plot" function. Since the "robot_stop.py" module contains code to draw figures using pygame, it is making it a bit difficult to just output the "stop" boolean value that will be used in the "herc_nav.py" file for navigation. This is found under the dev branch in the src file

**Comment by jay3ss** [comment]
So, I cloned your repo and (hopefully) installed all of your external Python dependencies (Pygame and NumPy). How am I supposed to run your code that you want help with? Is there a launch file or certain set of nodes that I'm supposed to run?

**Comment by jay3ss** [comment]
I was having some trouble getting ROS to [work with `virtualenv`](http://docs.python-guide.org/en/latest/dev/virtualenvs/) so (I hope that you don't mind) I added a few things to get things going for me that I'll put into a pull request.

**Comment by jreyes81** [comment]
Hey josh, so as of now the radar display can be run on its own. The file "Radar_Node.py" starts the radar display code and calls in the "pygame_radar.py" file to run it. So i just chmod the radar_node file and ran it.

**Comment by jreyes81** [comment]
There is no data plotted on the display since no hardware is being used to interfaced with the software. I have been only testing the functionality of the stop button

**Comment by jay3ss** [comment]
I'm not really understanding what the problem is. I run the `Radar_node.py` node, it opens the display, I click the stop button and then it prints out `Robot has stopped moving!` What are you expecting it to do?
