### ISSUE TITLE
Help with rospy publisher

### ISSUE THREAD

**Issue by jreyes81** [jreyes81/rescuerobot#5]
Hey Josh,

I was wondering if you could take a look at my code when I try to publish data to a topic I created. The two files I've been having problems with are the "pygame_radar.py" file and the "Radar_node.py" file. The way this is set up is that I have pygame radar imported to the Radar_Node file.

In "pygame_radar.py", I am getting a bit confused If I set up the publishing part of ROS right. In line 59, I want to publish my information from the stop button to the topic "cmd_stop" that should carry boolean values True or False. In line 64 I want to return the information used to create the message topic (self.cmd_stop) and the actual boolean values that appear when I press the stop button (self.stop).

In "Radar_Node.py" I initialize the radar display node. In line 20 I call the "RadarDisplay" class from the pygame radar file and assign my two variables that will contain information from the output. "Stop" contains the "self.stop" information and "cmd_stop" contains the "self.cmd_stop" information. I then try to publish what I want, but it isn’t' coming out like I thought it was.

Maybe I didn't set up the "Radar_Node.py" file correct as well. Thanks in advance for the help.

**Comment by jay3ss** [comment]
> I then try to publish what I want, but it isn’t' coming out like I thought it was.

What does this mean? What are you trying to publish and what is the result (and what are you expecting it to do)? Also, can you include some links to the lines of code that you're referring to? And what branch is this happening on?

**Comment by jreyes81** [comment]
So for the "pygame_radar.py" file. I am unsure for the following line of code:
(1) https://github.com/jreyes81/rescuerobot/blob/6cad73bd1e284fb67a8295fb12d49c47715985dd/src/pygame_radar.py#L59
In the same file, the code below is what im outputting from the RadarDisplay class of the file:
(2)
https://github.com/jreyes81/rescuerobot/blob/6cad73bd1e284fb67a8295fb12d49c47715985dd/src/pygame_radar.py#L64

Then in the "Radar_Node.py" file, I assign two variables to the two outputs from the (2) link:
https://github.com/jreyes81/rescuerobot/blob/6cad73bd1e284fb67a8295fb12d49c47715985dd/src/Radar_Node.py#L20

When I run `rostopic echo /cmd_stop` I expect to receive the output from the "stop" output and see a bunch of True and False's come out. Unfortunately, I don't see anything

**Comment by jreyes81** [comment]
All of this is in the "dev" branch. For the self.stop I initialized it to False and it changes to True whenever I click on the "stop" button of the radar display.

**Comment by jreyes81** [comment]
For the Radar_Node file, this is what i have for the code:
`def Radar_Node():
	#stop,cmd_stop = RadarDisplay()
	rospy.init_node("radar_display", anonymous=True)
	#radar_display = RadarDisplay() # Calls RadarDisplay class
	stop,cmd_stop = RadarDisplay()

	rate = rospy.Rate(10) # 10 Hz

	while not rospy.is_shutdown():
	    cmd_stop.publish(stop)
	    rate.sleep()

	#rospy.spin

if __name__ == '__main__':
	Radar_Node()`

**Comment by jay3ss** [comment]
So nothing is being published?

**Comment by jreyes81** [comment]
Nothing is being published. Which is why maybe I thought i set up or did something wrong, or forgot something. As of now, the stop button can be used without any hardware. I echoed the "cmd_stop" topic to see the data being published, but nothing was coming out

**Comment by jay3ss** [comment]
@jreyes81 Did we fix this on Saturday or are you still having this issue?

**Comment by jreyes81** [comment]
We fixed the issue. I forgot to close it. Thanks for your help

**Comment by jay3ss** [comment]
Np.
